export default {
    '/': '首页',
    '/home/': '首页',
    '/menubar/': '菜单中心',
    '/menubar/public/': '统一菜单',
    '/menubar/public/details/': '详情',
    '/menubar/private/': '我的菜单',
    '/menubar/private/new/': '新增',
    '/menubar/private/details/': '详情',
    '/menubar/template/': '详情',
    '/menubar/template/new/': '详情',
    '/accSupermarket/': '辅料超市',
    '/purOrder/': '采购订单',
    '/purOrder/new/': '新建订单',
    '/purOrder/details/': '详情',
    '/delivery/': '配送验收',
    '/parameter/': '台帐',
    '/parameter/purcatalog/': '采购目录',
    '/parameter/details/': '详情',
    '/setting/information/': '设置',
    '/setting/set/': '设置',
    '/setting/security/': '设置',
    '/setting/cuisine/': '设置',
    '/setting/': '设置',
}